common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'finance' %>
  password: <%= ENV['TRAVIS'] ? '' : 'finance' %>

development:
  database: finance_development
  <<: *common

test:
  database: finance_test
  <<: *common

production:
  database: finance_production
  <<: *common

sandbox:
  database: finance_production
  <<: *common
